language: node_js
node_js:
  - 10

install:
  - npm install -g codecov
  - npm install -g istanbul
script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
